# Setup
title:        TascMaster
tagline:      The Easiest Time Tracker. Period.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Pierre Tasci
  url:        http://pierretasci.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
